project:
  type: website
  output-dir: docs
  
website:
  title: "Neerav Karani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: interesting-blogs.qmd
        text: Interesting Blogs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  enabled: false